### ISSUE TITLE
cannot install on mac os with  Rstudio 1.0.44

### ISSUE THREAD

**Issue by hugh1li** [cole-brokamp/aiRpollution#1]
ERROR: dependency ‘CB’ is not available for package ‘aiRpollution’

**Comment by cole-brokamp** [comment]
try installing `CB` first with `devtools::install_github('cole-brokamp/CB')`

**Comment by cole-brokamp** [comment]
@hugh1li thanks for pointing this out, I am updating the package to prevent this error in the future.  should be up soon

**Comment by hugh1li** [comment]
I am actually looking at your AE paper. Could you share me with the LUR and LURF source code to hugh1li@cmu.edu, so I can use it for my LUR model development?

**Comment by cole-brokamp** [comment]
sure thing, just sent you an email.
